sudo: required
services:
  - docker
env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3-pip
    - python3.5
    - g++-7
    - doxygen

language: c

before_install:
  - export CC=gcc-7
  - export CXX=g++-7
  - sudo ln -sf /usr/bin/python3.5 /usr/bin/python3
  - sudo pip3 install meson
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - sudo cp ninja /usr/bin
  - wget http://http.debian.net/debian/pool/main/c/cyrus-sasl2/cyrus-sasl2_2.1.27~101-g0780600+dfsg.orig.tar.xz
  - tar xfv cyrus-sasl2_2.1.27~101-g0780600+dfsg.orig.tar.xz
  - pushd cyrus-sasl2-2.1.27~101-g0780600+dfsg.orig && ./autogen.sh && make && sudo make install && popd

install:
  - sudo apt install -y libssl-dev libsqlite3-dev libbz2-dev zlib1g-dev python3.5-dev
  - docker pull $DOCKER_IMAGE

script:
  - mkdir -p builddir && cd builddir && meson && ninja -v && sudo ninja install
  - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
  - sudo ldconfig -v
  - cd ../docs
  - doxygen
  - cd ../python
  - virtualenv -p /usr/bin/python3.5 venv
  - source venv/bin/activate
  - pip install tox
  - tox
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD sh -c 'ls /io/'
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD sh -c 'ls /io/travis'
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
